version: '3'
services:
  web:
    build:
      context: Pathfinder
    ports:
      - "80:80"
    environment:
      NGINX_HTTP_PORT: 80

      MYSQL_PATHFINDER_DBNAME: pathfinder
      MYSQL_PATHFINDER_USER: pathfinder
      MYSQL_PATHFINDER_PASSWORD: PFDB-password change this
      MYSQL_PATHFINDER_HOST: pf-db

      MYSQL_UNIVERSE_DBNAME: pathfinder
      MYSQL_UNIVERSE_USER: pathfinder
      MYSQL_UNIVERSE_PASSWORD: PFDB-password change this
      MYSQL_UNIVERSE_HOST: pf-db

      MYSQL_STATIC_DBNAME: pathfinder-static
      MYSQL_STATIC_USER: pathfinder-static
      MYSQL_STATIC_PASSWORD: PFSTATICDB-password change this
      MYSQL_STATIC_HOST: pf-static
      
      
      ADMIN_PASSWORD: ADMIN-PASSWORD change this
      SERVERURL: SERVERURL-change this
      SSO_CLIENTID: SSO_CLIENTID-change this
      SSO_SECRETKEY: SSO_CLIENTID-change this
    links:
      - pf-db
      - pf-static
  pf-db:
    image: mariadb:latest
    volumes:
      - pf-db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: pathfinder
      MYSQL_USER: pathfinder
      MYSQL_PASSWORD: PFDB-password change this
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  pf-static:
    build:
      context: Pathfinder-db
    volumes:
      - pf-static-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: pathfinder-static
      MYSQL_USER: pathfinder-static
      MYSQL_PASSWORD: PFSTATICDB-password change this
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
volumes:
  pf-db-data:
  pf-static-data: